//auth
export const REQUEST_AUTH = "REQUEST_AUTH";
export const REQUEST_AUTH_COMPLETED = "REQUEST_AUTH_COMPLETED";
export const REQUEST_EVENTS = "REQUEST_EVENTS";
export const REQUEST_EVENTS_COMPLETED = "REQUEST_EVENTS_COMPLETED";

export const REQUEST_ADD_CALENDAR = "REQUEST_ADD_CALENDAR";
export const REQUEST_ADD_CALENDAR_COMPLETED = "REQUEST_ADD_CALENDAR_COMPLETED";
