//auth
export const REQUEST_AUTH = "REQUEST_AUTH";
export const REQUEST_AUTH_COMPLETED = "REQUEST_AUTH_COMPLETED";
export const REQUEST_EVENTS = "REQUEST_EVENTS";
export const REQUEST_EVENTS_COMPLETED = "REQUEST_EVENTS_COMPLETED";

export const REQUEST_ADD_CALENDAR = "REQUEST_ADD_CALENDAR";
export const REQUEST_ADD_CALENDAR_COMPLETED = "REQUEST_ADD_CALENDAR_COMPLETED";

export const REQUEST_ADD_EVENT = "REQUEST_ADD_EVENT";
export const REQUEST_ADD_EVENT_COMPLETED = "REQUEST_ADD_EVENT_COMPLETED";

export const REQUEST_DELETE_EVENT = "REQUEST_DELETE_EVENT";
export const REQUEST_DELETE_EVENT_COMPLETED = "REQUEST_DELETE_EVENT_COMPLETED";

export const REQUEST_UPDATE_EVENT = "REQUEST_UPDATE_EVENT";
export const REQUEST_UPDATE_EVENT_COMPLETED = "REQUEST_UPDATE_EVENT_COMPLETED";

export const REQUEST_ADD_CONTACT = "REQUEST_ADD_CONTACT";
export const REQUEST_ADD_CONTACT_COMPLETED = "REQUEST_ADD_CONTACT_COMPLETED";
export const REQUEST_UPDATE_CONTACT = "REQUEST_UPDATE_CONTACT";
export const REQUEST_UPDATE_CONTACT_COMPLETED =
  "REQUEST_UPDATE_CONTACT_COMPLETED";
export const REQUEST_REMOVE_CONTACT = "REQUEST_REMOVE_CONTACT";
export const REQUEST_REMOVE_CONTACT_COMPLETED =
  "REQUEST_REMOVE_CONTACT_COMPLETED";

export const REQUEST_ADD_GROUP = "REQUEST_ADD_GROUP";
export const REQUEST_ADD_GROUP_COMPLETED = "REQUEST_ADD_GROUP_COMPLETED";
export const REQUEST_UPDATE_GROUP = "REQUEST_UPDATE_GROUP";
export const REQUEST_UPDATE_GROUP_COMPLETED = "REQUEST_UPDATE_GROUP_COMPLETED";

export const REQUEST_ADD_RELATIVE = "REQUEST_ADD_RELATIVE";
export const REQUEST_ADD_RELATIVE_COMPLETED = "REQUEST_ADD_RELATIVE_COMPLETED";
