import * as actionType from "../actions/Constant";

export default function Applications(
  state = {
    gradeList: [],
    individualList: null
  },
  action
) {
  switch (action.type) {
    case actionType.CUMULATIVE_GRADE_BY_APP_GROUP_COMPLETED:
      return {
        ...state,
        gradeList: action.payload
      }
    case actionType.CUMULATIVE_GRADE_BY_USER_COMPLETED: 
      return {
        ...state,
        individualList: action.payload
        // individualList: {
        //   cumulative_grades: [
        //     {
        //       "student_grade_cumulative_id": 2,
        //       "app_group_id": null,
        //       "app_group_name": null,
        //       "application_type": "bcombs",
        //       "child_id": "231d28bb-1f92-11eb-8212-dafd2d0ae3ff",
        //       "form_contents": null,
        //       "year_level": 5,
        //       "designation": null,
        //       "school_type": "Test",
        //       "school_name": "Harvard",
        //       "school_year_start": 2018,
        //       "school_year_end": 2019,
        //       "school_year_frame": "quarter",
        //       "class_name": "Test",
        //       "class_type": "Test",
        //       "class_teacher": null,
        //       "attachment": null,
        //       "firstname": "John",
        //       "lastname": "Doe",
        //       "scale": 0,
        //       "grades": [
        //         {
        //           "student_grade_cumulative_id": 2,
        //           "class": "Basic Programming",
        //           "subject": "Basic Programming",
        //           "teacher_name": "Test",
        //           "designation": "Test",
        //           "grade_quarter_1": 88,
        //           "grade_quarter_2": 89,
        //           "grade_quarter_3": 90,
        //           "grade_quarter_4": 86,
        //           "letter_grade_quarter_1": "A",
        //           "letter_grade_quarter_2": "B",
        //           "letter_grade_quarter_3": "C",
        //           "letter_grade_quarter_4": "B",
        //           "attendance_quarter_1_total": 40,
        //           "attendance_quarter_2_total": 40,
        //           "attendance_quarter_3_total": 37,
        //           "attendance_quarter_4_total": 38,
        //           "attendance_quarter_1_absent": 2,
        //           "attendance_quarter_2_absent": 3,
        //           "attendance_quarter_3_absent": 4,
        //           "attendance_quarter_4_absent": 1,
        //           "attendance_quarter_1_tardy": 1,
        //           "attendance_quarter_2_tardy": 2,
        //           "attendance_quarter_3_tardy": 3,
        //           "attendance_quarter_4_tardy": 2,
        //           "attendance_quarter_1_present": 37,
        //           "attendance_quarter_2_present": 35,
        //           "attendance_quarter_3_present": 30,
        //           "attendance_quarter_4_present": 35,
        //           "final_grade": 87,
        //           "letter_final_grade": "C",
        //           "year_final_grade": 85,
        //           "quarter_average": 96.25,
        //           "semestral_1_average": null,
        //           "semestral_2_average": null,
        //           "semestral_final": null,
        //           "final_semestral_1_attendance": null,
        //           "final_semestral_2_attendance": null,
        //           "final_quarter_attendance": 100,
        //           "attendance": null
        //         },
        //         {
        //           "student_grade_cumulative_id": 2,
        //           "class": "Math",
        //           "subject": "Math",
        //           "teacher_name": "Test",
        //           "designation": "Test",
        //           "grade_quarter_1": 95,
        //           "grade_quarter_2": 92,
        //           "grade_quarter_3": 89,
        //           "grade_quarter_4": 99,
        //           "letter_grade_quarter_1": "B",
        //           "letter_grade_quarter_2": "A",
        //           "letter_grade_quarter_3": "A",
        //           "letter_grade_quarter_4": "A",
        //           "attendance_quarter_1_total": 40,
        //           "attendance_quarter_2_total": 39,
        //           "attendance_quarter_3_total": 40,
        //           "attendance_quarter_4_total": 38,
        //           "attendance_quarter_1_absent": 2,
        //           "attendance_quarter_2_absent": 3,
        //           "attendance_quarter_3_absent": 4,
        //           "attendance_quarter_4_absent": 1,
        //           "attendance_quarter_1_tardy": 1,
        //           "attendance_quarter_2_tardy": 2,
        //           "attendance_quarter_3_tardy": 3,
        //           "attendance_quarter_4_tardy": 2,
        //           "attendance_quarter_1_present": 37,
        //           "attendance_quarter_2_present": 35,
        //           "attendance_quarter_3_present": 30,
        //           "attendance_quarter_4_present": 35,
        //           "final_grade": 98,
        //           "letter_final_grade": "B",
        //           "year_final_grade": 90,
        //           "quarter_average": 96.25,
        //           "semestral_1_average": null,
        //           "semestral_2_average": null,
        //           "semestral_final": null,
        //           "final_semestral_1_attendance": null,
        //           "final_semestral_2_attendance": null,
        //           "final_quarter_attendance": 150,
        //           "attendance": null
        //         }
        //       ]
        //     },
        //     {
        //       "student_grade_cumulative_id": 3,
        //       "app_group_id": null,
        //       "app_group_name": null,
        //       "application_type": "bcombs",
        //       "child_id": "231d28bb-1f92-11eb-8212-dafd2d0ae3ff",
        //       "form_contents": null,
        //       "year_level": 6,
        //       "designation": null,
        //       "school_type": "Test",
        //       "school_name": "Harvard",
        //       "school_year_start": 2019,
        //       "school_year_end": 2020,
        //       "school_year_frame": "quarter",
        //       "class_name": "Test",
        //       "class_type": "Test",
        //       "class_teacher": null,
        //       "attachment": null,
        //       "firstname": "John",
        //       "lastname": "Doe",
        //       "scale": 0,
        //       "grades": [
        //         {
        //           "student_grade_cumulative_id": 3,
        //           "class": "Basic Programming",
        //           "subject": "Basic Programming",
        //           "teacher_name": "Test",
        //           "designation": "Test",
        //           "grade_quarter_1": 90,
        //           "grade_quarter_2": 89,
        //           "grade_quarter_3": 98,
        //           "grade_quarter_4": 88,
        //           "letter_grade_quarter_1": "C",
        //           "letter_grade_quarter_2": "A",
        //           "letter_grade_quarter_3": "C",
        //           "letter_grade_quarter_4": "A",
        //           "attendance_quarter_1_total": 37,
        //           "attendance_quarter_2_total": 40,
        //           "attendance_quarter_3_total": 35,
        //           "attendance_quarter_4_total": 38,
        //           "attendance_quarter_1_absent": 2,
        //           "attendance_quarter_2_absent": 3,
        //           "attendance_quarter_3_absent": 4,
        //           "attendance_quarter_4_absent": 1,
        //           "attendance_quarter_1_tardy": 1,
        //           "attendance_quarter_2_tardy": 2,
        //           "attendance_quarter_3_tardy": 3,
        //           "attendance_quarter_4_tardy": 2,
        //           "attendance_quarter_1_present": 37,
        //           "attendance_quarter_2_present": 35,
        //           "attendance_quarter_3_present": 30,
        //           "attendance_quarter_4_present": 35,
        //           "final_grade": 93,
        //           "letter_final_grade": "A",
        //           "year_final_grade": 95,
        //           "quarter_average": 96.25,
        //           "semestral_1_average": null,
        //           "semestral_2_average": null,
        //           "semestral_final": null,
        //           "final_semestral_1_attendance": null,
        //           "final_semestral_2_attendance": null,
        //           "final_quarter_attendance": 149,
        //           "attendance": null
        //         },
        //         {
        //           "student_grade_cumulative_id": 3,
        //           "class": "Math",
        //           "subject": "Math",
        //           "teacher_name": "Test",
        //           "designation": "Test",
        //           "grade_quarter_1": 80,
        //           "grade_quarter_2": 89,
        //           "grade_quarter_3": 90,
        //           "grade_quarter_4": 85,
        //           "letter_grade_quarter_1": "C",
        //           "letter_grade_quarter_2": "A",
        //           "letter_grade_quarter_3": "C",
        //           "letter_grade_quarter_4": "A",
        //           "attendance_quarter_1_total": 35,
        //           "attendance_quarter_2_total": 30,
        //           "attendance_quarter_3_total": 40,
        //           "attendance_quarter_4_total": 38,
        //           "attendance_quarter_1_absent": 2,
        //           "attendance_quarter_2_absent": 3,
        //           "attendance_quarter_3_absent": 4,
        //           "attendance_quarter_4_absent": 1,
        //           "attendance_quarter_1_tardy": 1,
        //           "attendance_quarter_2_tardy": 2,
        //           "attendance_quarter_3_tardy": 3,
        //           "attendance_quarter_4_tardy": 2,
        //           "attendance_quarter_1_present": 37,
        //           "attendance_quarter_2_present": 35,
        //           "attendance_quarter_3_present": 30,
        //           "attendance_quarter_4_present": 35,
        //           "final_grade": 95,
        //           "letter_final_grade": "B",
        //           "year_final_grade": 90,
        //           "quarter_average": 96.25,
        //           "semestral_1_average": null,
        //           "semestral_2_average": null,
        //           "semestral_final": null,
        //           "final_semestral_1_attendance": null,
        //           "final_semestral_2_attendance": null,
        //           "final_quarter_attendance": 130,
        //           "attendance": null
        //         }
        //       ]
        //     }
        //   ]
        // }
      }
    default:
      return state;
  }
}
