import * as actionType from "../actions/Constant";

export default function Applications(
  state = {
    gradeList: [],
    individualList: null,
    stUpdated: false,
    addUpdate: null
  },
  action
) {
  switch (action.type) {
    case actionType.CUMULATIVE_GRADE_BY_APP_GROUP_COMPLETED:
      return {
        ...state,
        gradeList: [
          {
              "app_group_id": "97754eb9-fc18-11ea-8212-dafd2d0ae3ff",
              "app_group_name": "New group",
              "app_id": "77061ec7-1f90-11eb-8212-dafd2d0ae3ff",
              "child_id": "77031f17-1f90-11eb-8212-dafd2d0ae3ff",
              "firstname": "kkjk",
              "lastname": "jkjjj",
              "form_contents": null,
              "cumulative_grades": [
                  {
                      "student_grade_cumulative_id": 2,
                      "app_id": null,
                      "app_group_id": "97754eb9-fc18-11ea-8212-dafd2d0ae3ff",
                      "app_group_name": null,
                      "application_type": "bcombs",
                      "child_id": "77031f17-1f90-11eb-8212-dafd2d0ae3ff",
                      "form_contents": null,
                      "year_level": 5,
                      "designation": null,
                      "school_type": "Test",
                      "school_name": "Harvard",
                      "school_year_start": 2015,
                      "school_year_end": 2016,
                      "school_year_frame": "quarter",
                      "class_name": "Test",
                      "class_type": "Test",
                      "class_teacher": null,
                      "attachment": null,
                      "firstname": null,
                      "lastname": null,
                      "gpa_sem_1": 0,
                      "gpa_sem_2": 0,
                      "gpa_final": 0,
                      "scale": 0,
                      "grades": [
                          {
                              "student_grade_cumulative_id": 2,
                              "class": "Basic Programming",
                              "subject": "Basic Programming",
                              "teacher_name": "Test",
                              "designation": "Test",
                              "grade_quarter_1": 99,
                              "grade_quarter_2": 99,
                              "grade_quarter_3": 99,
                              "grade_quarter_4": 88,
                              "letter_grade_quarter_1": "A",
                              "letter_grade_quarter_2": "B",
                              "letter_grade_quarter_3": "C",
                              "letter_grade_quarter_4": "B",
                              "attendance_quarter_1_total": 40,
                              "attendance_quarter_2_total": 40,
                              "attendance_quarter_3_total": 37,
                              "attendance_quarter_4_total": 38,
                              "attendance_quarter_1_absent": 2,
                              "attendance_quarter_2_absent": 3,
                              "attendance_quarter_3_absent": 4,
                              "attendance_quarter_4_absent": 1,
                              "attendance_quarter_1_tardy": 1,
                              "attendance_quarter_2_tardy": 2,
                              "attendance_quarter_3_tardy": 3,
                              "attendance_quarter_4_tardy": 2,
                              "attendance_quarter_1_present": 37,
                              "attendance_quarter_2_present": 35,
                              "attendance_quarter_3_present": 30,
                              "attendance_quarter_4_present": 35,
                              "final_grade": 90,
                              "year_final_grade": 87,
                              "quarter_average": 96.25,
                              "semestral_1_average": null,
                              "semestral_2_average": null,
                              "semestral_final": null,
                              "final_semestral_1_attendance": null,
                              "final_semestral_2_attendance": null,
                              "final_quarter_attendance": 155,
                              "mid_quarter_remarks": null,
                              "final_quarter_remarks": null,
                              "attendance": null
                          }
                      ]
                  },
                  {
                      "student_grade_cumulative_id": 11,
                      "app_id": null,
                      "app_group_id": "97754eb9-fc18-11ea-8212-dafd2d0ae3ff",
                      "app_group_name": null,
                      "application_type": "bcombs",
                      "child_id": "77031f17-1f90-11eb-8212-dafd2d0ae3ff",
                      "form_contents": null,
                      "year_level": 5,
                      "designation": null,
                      "school_type": "Test",
                      "school_name": "Harvard",
                      "school_year_start": 2016,
                      "school_year_end": 2017,
                      "school_year_frame": "quarter",
                      "class_name": "Test",
                      "class_type": "Test",
                      "class_teacher": null,
                      "attachment": null,
                      "firstname": null,
                      "lastname": null,
                      "gpa_sem_1": 0,
                      "gpa_sem_2": 0,
                      "gpa_final": 0,
                      "scale": 1,
                      "grades": [
                          {
                              "student_grade_cumulative_id": 11,
                              "class": "Basic Programming",
                              "subject": "Basic Programming",
                              "teacher_name": "Test",
                              "designation": "Test",
                              "grade_quarter_1": 99,
                              "grade_quarter_2": 99,
                              "grade_quarter_3": 99,
                              "grade_quarter_4": 88,
                              "letter_grade_quarter_1": "A",
                              "letter_grade_quarter_2": "B",
                              "letter_grade_quarter_3": "C",
                              "letter_grade_quarter_4": "B",
                              "attendance_quarter_1_total": 40,
                              "attendance_quarter_2_total": 40,
                              "attendance_quarter_3_total": 37,
                              "attendance_quarter_4_total": 38,
                              "attendance_quarter_1_absent": 2,
                              "attendance_quarter_2_absent": 3,
                              "attendance_quarter_3_absent": 4,
                              "attendance_quarter_4_absent": 1,
                              "attendance_quarter_1_tardy": 1,
                              "attendance_quarter_2_tardy": 2,
                              "attendance_quarter_3_tardy": 3,
                              "attendance_quarter_4_tardy": 2,
                              "attendance_quarter_1_present": 37,
                              "attendance_quarter_2_present": 35,
                              "attendance_quarter_3_present": 30,
                              "attendance_quarter_4_present": 35,
                              "final_grade": 90,
                              "year_final_grade": 87,
                              "quarter_average": 96.25,
                              "semestral_1_average": null,
                              "semestral_2_average": null,
                              "semestral_final": null,
                              "final_semestral_1_attendance": null,
                              "final_semestral_2_attendance": null,
                              "final_quarter_attendance": 155,
                              "mid_quarter_remarks": null,
                              "final_quarter_remarks": null,
                              "attendance": null
                          }
                      ]
                  },
                  {
                      "student_grade_cumulative_id": 12,
                      "app_id": null,
                      "app_group_id": "97754eb9-fc18-11ea-8212-dafd2d0ae3ff",
                      "app_group_name": null,
                      "application_type": "bcombs",
                      "child_id": "77031f17-1f90-11eb-8212-dafd2d0ae3ff",
                      "form_contents": null,
                      "year_level": 5,
                      "designation": null,
                      "school_type": "Test",
                      "school_name": "Harvard",
                      "school_year_start": 2017,
                      "school_year_end": 2018,
                      "school_year_frame": "quarter",
                      "class_name": "Test",
                      "class_type": "Test",
                      "class_teacher": null,
                      "attachment": null,
                      "firstname": null,
                      "lastname": null,
                      "gpa_sem_1": 0,
                      "gpa_sem_2": 0,
                      "gpa_final": 0,
                      "scale": 1.5,
                      "grades": [
                          {
                              "student_grade_cumulative_id": 12,
                              "class": "Basic Programming",
                              "subject": "Basic Programming",
                              "teacher_name": "Test",
                              "designation": "Test",
                              "grade_quarter_1": 99,
                              "grade_quarter_2": 99,
                              "grade_quarter_3": 99,
                              "grade_quarter_4": 88,
                              "letter_grade_quarter_1": "A",
                              "letter_grade_quarter_2": "B",
                              "letter_grade_quarter_3": "C",
                              "letter_grade_quarter_4": "B",
                              "attendance_quarter_1_total": 40,
                              "attendance_quarter_2_total": 40,
                              "attendance_quarter_3_total": 37,
                              "attendance_quarter_4_total": 38,
                              "attendance_quarter_1_absent": 2,
                              "attendance_quarter_2_absent": 3,
                              "attendance_quarter_3_absent": 4,
                              "attendance_quarter_4_absent": 1,
                              "attendance_quarter_1_tardy": 1,
                              "attendance_quarter_2_tardy": 2,
                              "attendance_quarter_3_tardy": 3,
                              "attendance_quarter_4_tardy": 2,
                              "attendance_quarter_1_present": 37,
                              "attendance_quarter_2_present": 35,
                              "attendance_quarter_3_present": 30,
                              "attendance_quarter_4_present": 35,
                              "final_grade": 90,
                              "year_final_grade": 87,
                              "quarter_average": 96.25,
                              "semestral_1_average": null,
                              "semestral_2_average": null,
                              "semestral_final": null,
                              "final_semestral_1_attendance": null,
                              "final_semestral_2_attendance": null,
                              "final_quarter_attendance": 155,
                              "mid_quarter_remarks": null,
                              "final_quarter_remarks": null,
                              "attendance": null
                          }
                      ]
                  },
                  {
                      "student_grade_cumulative_id": 13,
                      "app_id": null,
                      "app_group_id": "97754eb9-fc18-11ea-8212-dafd2d0ae3ff",
                      "app_group_name": null,
                      "application_type": "bcombs",
                      "child_id": "77031f17-1f90-11eb-8212-dafd2d0ae3ff",
                      "form_contents": null,
                      "year_level": 5,
                      "designation": null,
                      "school_type": "Test",
                      "school_name": "Harvard",
                      "school_year_start": 2018,
                      "school_year_end": 2019,
                      "school_year_frame": "quarter",
                      "class_name": "Test",
                      "class_type": "Test",
                      "class_teacher": null,
                      "attachment": null,
                      "firstname": null,
                      "lastname": null,
                      "gpa_sem_1": 0,
                      "gpa_sem_2": 0,
                      "gpa_final": 0,
                      "scale": 1,
                      "grades": [
                          {
                              "student_grade_cumulative_id": 13,
                              "class": "Basic Programming",
                              "subject": "Basic Programming",
                              "teacher_name": "Test",
                              "designation": "Test",
                              "grade_quarter_1": 99,
                              "grade_quarter_2": 99,
                              "grade_quarter_3": 99,
                              "grade_quarter_4": 88,
                              "letter_grade_quarter_1": "A",
                              "letter_grade_quarter_2": "B",
                              "letter_grade_quarter_3": "C",
                              "letter_grade_quarter_4": "B",
                              "attendance_quarter_1_total": 40,
                              "attendance_quarter_2_total": 40,
                              "attendance_quarter_3_total": 37,
                              "attendance_quarter_4_total": 38,
                              "attendance_quarter_1_absent": 2,
                              "attendance_quarter_2_absent": 3,
                              "attendance_quarter_3_absent": 4,
                              "attendance_quarter_4_absent": 1,
                              "attendance_quarter_1_tardy": 1,
                              "attendance_quarter_2_tardy": 2,
                              "attendance_quarter_3_tardy": 3,
                              "attendance_quarter_4_tardy": 2,
                              "attendance_quarter_1_present": 37,
                              "attendance_quarter_2_present": 35,
                              "attendance_quarter_3_present": 30,
                              "attendance_quarter_4_present": 35,
                              "final_grade": 90,
                              "year_final_grade": 87,
                              "quarter_average": 96.25,
                              "semestral_1_average": null,
                              "semestral_2_average": null,
                              "semestral_final": null,
                              "final_semestral_1_attendance": null,
                              "final_semestral_2_attendance": null,
                              "final_quarter_attendance": 155,
                              "mid_quarter_remarks": null,
                              "final_quarter_remarks": null,
                              "attendance": null
                          }
                      ]
                  },
                  {
                      "student_grade_cumulative_id": 14,
                      "app_id": null,
                      "app_group_id": "97754eb9-fc18-11ea-8212-dafd2d0ae3ff",
                      "app_group_name": null,
                      "application_type": "bcombs",
                      "child_id": "77031f17-1f90-11eb-8212-dafd2d0ae3ff",
                      "form_contents": null,
                      "year_level": 5,
                      "designation": null,
                      "school_type": "Test",
                      "school_name": "Harvard",
                      "school_year_start": 2020,
                      "school_year_end": 2021,
                      "school_year_frame": "quarter",
                      "class_name": "Test",
                      "class_type": "Test",
                      "class_teacher": null,
                      "attachment": null,
                      "firstname": null,
                      "lastname": null,
                      "gpa_sem_1": 80,
                      "gpa_sem_2": 81,
                      "gpa_final": 82,
                      "scale": 1,
                      "grades": [
                          {
                              "student_grade_cumulative_id": 14,
                              "class": "Basic Programming",
                              "subject": "Basic Programming",
                              "teacher_name": "Test",
                              "designation": "Test",
                              "grade_quarter_1": 99,
                              "grade_quarter_2": 99,
                              "grade_quarter_3": 99,
                              "grade_quarter_4": 88,
                              "letter_grade_quarter_1": "A",
                              "letter_grade_quarter_2": "B",
                              "letter_grade_quarter_3": "C",
                              "letter_grade_quarter_4": "B",
                              "attendance_quarter_1_total": 40,
                              "attendance_quarter_2_total": 40,
                              "attendance_quarter_3_total": 37,
                              "attendance_quarter_4_total": 38,
                              "attendance_quarter_1_absent": 2,
                              "attendance_quarter_2_absent": 3,
                              "attendance_quarter_3_absent": 4,
                              "attendance_quarter_4_absent": 1,
                              "attendance_quarter_1_tardy": 1,
                              "attendance_quarter_2_tardy": 2,
                              "attendance_quarter_3_tardy": 3,
                              "attendance_quarter_4_tardy": 2,
                              "attendance_quarter_1_present": 37,
                              "attendance_quarter_2_present": 35,
                              "attendance_quarter_3_present": 30,
                              "attendance_quarter_4_present": 35,
                              "final_grade": 90,
                              "year_final_grade": 87,
                              "quarter_average": 96.25,
                              "semestral_1_average": null,
                              "semestral_2_average": null,
                              "semestral_final": null,
                              "final_semestral_1_attendance": null,
                              "final_semestral_2_attendance": null,
                              "final_quarter_attendance": 155,
                              "mid_quarter_remarks": "Passed",
                              "final_quarter_remarks": "Passed",
                              "attendance": null
                          }
                      ]
                  },
                  {
                      "student_grade_cumulative_id": 15,
                      "app_id": null,
                      "app_group_id": "97754eb9-fc18-11ea-8212-dafd2d0ae3ff",
                      "app_group_name": null,
                      "application_type": "bcombs",
                      "child_id": "77031f17-1f90-11eb-8212-dafd2d0ae3ff",
                      "form_contents": null,
                      "year_level": 5,
                      "designation": null,
                      "school_type": "Test",
                      "school_name": "Harvard",
                      "school_year_start": 2020,
                      "school_year_end": 2021,
                      "school_year_frame": "quarter",
                      "class_name": "Test",
                      "class_type": "Test",
                      "class_teacher": null,
                      "attachment": null,
                      "firstname": null,
                      "lastname": null,
                      "gpa_sem_1": 80,
                      "gpa_sem_2": 81,
                      "gpa_final": 82,
                      "scale": 1,
                      "grades": [
                          {
                              "student_grade_cumulative_id": 15,
                              "class": "Basic Programming",
                              "subject": "Basic Programming",
                              "teacher_name": "Test",
                              "designation": "Test",
                              "grade_quarter_1": 99,
                              "grade_quarter_2": 99,
                              "grade_quarter_3": 99,
                              "grade_quarter_4": 88,
                              "letter_grade_quarter_1": "A",
                              "letter_grade_quarter_2": "B",
                              "letter_grade_quarter_3": "C",
                              "letter_grade_quarter_4": "B",
                              "attendance_quarter_1_total": 40,
                              "attendance_quarter_2_total": 40,
                              "attendance_quarter_3_total": 37,
                              "attendance_quarter_4_total": 38,
                              "attendance_quarter_1_absent": 2,
                              "attendance_quarter_2_absent": 3,
                              "attendance_quarter_3_absent": 4,
                              "attendance_quarter_4_absent": 1,
                              "attendance_quarter_1_tardy": 1,
                              "attendance_quarter_2_tardy": 2,
                              "attendance_quarter_3_tardy": 3,
                              "attendance_quarter_4_tardy": 2,
                              "attendance_quarter_1_present": 37,
                              "attendance_quarter_2_present": 35,
                              "attendance_quarter_3_present": 30,
                              "attendance_quarter_4_present": 35,
                              "final_grade": 90,
                              "year_final_grade": 87,
                              "quarter_average": 96.25,
                              "semestral_1_average": null,
                              "semestral_2_average": null,
                              "semestral_final": null,
                              "final_semestral_1_attendance": null,
                              "final_semestral_2_attendance": null,
                              "final_quarter_attendance": 155,
                              "mid_quarter_remarks": "Passed",
                              "final_quarter_remarks": "Passed",
                              "attendance": null
                          }
                      ]
                  }
              ],
              "standardized_test": [
                  {
                      "student_test_id": 8,
                      "child_id": "77031f17-1f90-11eb-8212-dafd2d0ae3ff",
                      "test_name": "act",
                      "attempt": 2,
                      "grade_taken": 0,
                      "month_taken": "05/01/2021",
                      "score": 10,
                      "score_percentage": 100,
                      "ach_level": 0,
                      "school_percentage": 0,
                      "nationality_percentage": 0,
                      "district_percentage": 0,
                      "state_percentage": 0,
                      "attachment": null
                  },
                  {
                      "student_test_id": 11,
                      "child_id": "77031f17-1f90-11eb-8212-dafd2d0ae3ff",
                      "test_name": "act",
                      "attempt": 1,
                      "grade_taken": 0,
                      "month_taken": "",
                      "score": 0,
                      "score_percentage": 0,
                      "ach_level": 0,
                      "school_percentage": 0,
                      "nationality_percentage": 0,
                      "district_percentage": 0,
                      "state_percentage": 0,
                      "attachment": null
                  },
                  {
                      "student_test_id": 14,
                      "child_id": "77031f17-1f90-11eb-8212-dafd2d0ae3ff",
                      "test_name": "act",
                      "attempt": 2,
                      "grade_taken": 0,
                      "month_taken": "",
                      "score": 40,
                      "score_percentage": 0,
                      "ach_level": 0,
                      "school_percentage": 0,
                      "nationality_percentage": 0,
                      "district_percentage": 0,
                      "state_percentage": 0,
                      "attachment": null
                  },
                  {
                      "student_test_id": 17,
                      "child_id": "77031f17-1f90-11eb-8212-dafd2d0ae3ff",
                      "test_name": "sat",
                      "attempt": 1,
                      "grade_taken": 0,
                      "month_taken": "01/01/2015",
                      "score": 10,
                      "score_percentage": 0,
                      "ach_level": 0,
                      "school_percentage": 0,
                      "nationality_percentage": 0,
                      "district_percentage": 0,
                      "state_percentage": 0,
                      "attachment": null
                  },
                  {
                      "student_test_id": 18,
                      "child_id": "77031f17-1f90-11eb-8212-dafd2d0ae3ff",
                      "test_name": "act",
                      "attempt": 1,
                      "grade_taken": 0,
                      "month_taken": "05/01/2015",
                      "score": 88,
                      "score_percentage": 0,
                      "ach_level": 0,
                      "school_percentage": 0,
                      "nationality_percentage": 0,
                      "district_percentage": 0,
                      "state_percentage": 0,
                      "attachment": null
                  },
                  {
                      "student_test_id": 21,
                      "child_id": "77031f17-1f90-11eb-8212-dafd2d0ae3ff",
                      "test_name": "act",
                      "attempt": 1,
                      "grade_taken": 0,
                      "month_taken": "05/01/2021",
                      "score": 99,
                      "score_percentage": 0,
                      "ach_level": 0,
                      "school_percentage": 0,
                      "nationality_percentage": 0,
                      "district_percentage": 0,
                      "state_percentage": 0,
                      "attachment": null
                  },
                  {
                      "student_test_id": 22,
                      "child_id": "77031f17-1f90-11eb-8212-dafd2d0ae3ff",
                      "test_name": "sat",
                      "attempt": 1,
                      "grade_taken": 0,
                      "month_taken": "09/01/2021",
                      "score": 77,
                      "score_percentage": 0,
                      "ach_level": 0,
                      "school_percentage": 0,
                      "nationality_percentage": 0,
                      "district_percentage": 0,
                      "state_percentage": 0,
                      "attachment": null
                  },
                  {
                      "student_test_id": 23,
                      "child_id": "77031f17-1f90-11eb-8212-dafd2d0ae3ff",
                      "test_name": "act",
                      "attempt": 3,
                      "grade_taken": 0,
                      "month_taken": "01/01/2021",
                      "score": 13,
                      "score_percentage": 13,
                      "ach_level": 13,
                      "school_percentage": 13,
                      "nationality_percentage": 13,
                      "district_percentage": 13,
                      "state_percentage": 13,
                      "attachment": null
                  },
                  {
                      "student_test_id": 24,
                      "child_id": "77031f17-1f90-11eb-8212-dafd2d0ae3ff",
                      "test_name": "act",
                      "attempt": 1,
                      "grade_taken": 0,
                      "month_taken": "",
                      "score": 0,
                      "score_percentage": 0,
                      "ach_level": 0,
                      "school_percentage": 0,
                      "nationality_percentage": 0,
                      "district_percentage": 0,
                      "state_percentage": 0,
                      "attachment": null
                  },
                  {
                      "student_test_id": 25,
                      "child_id": "77031f17-1f90-11eb-8212-dafd2d0ae3ff",
                      "test_name": "act",
                      "attempt": 4,
                      "grade_taken": 0,
                      "month_taken": "",
                      "score": 0,
                      "score_percentage": 0,
                      "ach_level": 0,
                      "school_percentage": 0,
                      "nationality_percentage": 0,
                      "district_percentage": 0,
                      "state_percentage": 0,
                      "attachment": null
                  },
                  {
                      "student_test_id": 29,
                      "child_id": "77031f17-1f90-11eb-8212-dafd2d0ae3ff",
                      "test_name": "act",
                      "attempt": 5,
                      "grade_taken": 0,
                      "month_taken": "02/01/2021",
                      "score": 0,
                      "score_percentage": 0,
                      "ach_level": 0,
                      "school_percentage": 0,
                      "nationality_percentage": 0,
                      "district_percentage": 0,
                      "state_percentage": 0,
                      "attachment": null
                  },
                  {
                      "student_test_id": 30,
                      "child_id": "77031f17-1f90-11eb-8212-dafd2d0ae3ff",
                      "test_name": "act",
                      "attempt": 6,
                      "grade_taken": 0,
                      "month_taken": "",
                      "score": 0,
                      "score_percentage": 0,
                      "ach_level": 0,
                      "school_percentage": 0,
                      "nationality_percentage": 0,
                      "district_percentage": 0,
                      "state_percentage": 0,
                      "attachment": null
                  },
                  {
                      "student_test_id": 31,
                      "child_id": "77031f17-1f90-11eb-8212-dafd2d0ae3ff",
                      "test_name": "act",
                      "attempt": 7,
                      "grade_taken": 0,
                      "month_taken": "",
                      "score": 0,
                      "score_percentage": 0,
                      "ach_level": 0,
                      "school_percentage": 0,
                      "nationality_percentage": 0,
                      "district_percentage": 0,
                      "state_percentage": 0,
                      "attachment": null
                  },
                  {
                      "student_test_id": 32,
                      "child_id": "77031f17-1f90-11eb-8212-dafd2d0ae3ff",
                      "test_name": "act",
                      "attempt": 8,
                      "grade_taken": 0,
                      "month_taken": "",
                      "score": 0,
                      "score_percentage": 0,
                      "ach_level": 0,
                      "school_percentage": 0,
                      "nationality_percentage": 0,
                      "district_percentage": 0,
                      "state_percentage": 0,
                      "attachment": null
                  },
                  {
                      "student_test_id": 34,
                      "child_id": "77031f17-1f90-11eb-8212-dafd2d0ae3ff",
                      "test_name": "act",
                      "attempt": 1,
                      "grade_taken": 5,
                      "month_taken": "2021-04-30T16:00:00.000Z",
                      "score": 20,
                      "score_percentage": 0,
                      "ach_level": 0,
                      "school_percentage": 0,
                      "nationality_percentage": 0,
                      "district_percentage": 0,
                      "state_percentage": 0,
                      "attachment": null
                  }
              ]
          },
          {
              "app_group_id": "97754eb9-fc18-11ea-8212-dafd2d0ae3ff",
              "app_group_name": "New group",
              "app_id": "23205833-1f92-11eb-8212-dafd2d0ae3ff",
              "child_id": "231d28bb-1f92-11eb-8212-dafd2d0ae3ff",
              "firstname": "erwerewr",
              "lastname": "ewrewrewr",
              "form_contents": null,
              "cumulative_grades": [
                  {
                      "student_grade_cumulative_id": 3,
                      "app_id": null,
                      "app_group_id": "97754eb9-fc18-11ea-8212-dafd2d0ae3ff",
                      "app_group_name": null,
                      "application_type": "bcombs",
                      "child_id": "231d28bb-1f92-11eb-8212-dafd2d0ae3ff",
                      "form_contents": null,
                      "year_level": 5,
                      "designation": null,
                      "school_type": "Test",
                      "school_name": "Harvard",
                      "school_year_start": 2020,
                      "school_year_end": 2021,
                      "school_year_frame": "quarter",
                      "class_name": "Test",
                      "class_type": "Test",
                      "class_teacher": null,
                      "attachment": null,
                      "firstname": null,
                      "lastname": null,
                      "gpa_sem_1": 0,
                      "gpa_sem_2": 0,
                      "gpa_final": 0,
                      "scale": 0,
                      "grades": [
                          {
                              "student_grade_cumulative_id": 3,
                              "class": "Basic Programming",
                              "subject": "Basic Programming",
                              "teacher_name": "Test",
                              "designation": "Test",
                              "grade_quarter_1": 99,
                              "grade_quarter_2": 99,
                              "grade_quarter_3": 99,
                              "grade_quarter_4": 88,
                              "letter_grade_quarter_1": "A",
                              "letter_grade_quarter_2": "B",
                              "letter_grade_quarter_3": "C",
                              "letter_grade_quarter_4": "B",
                              "attendance_quarter_1_total": 40,
                              "attendance_quarter_2_total": 40,
                              "attendance_quarter_3_total": 37,
                              "attendance_quarter_4_total": 38,
                              "attendance_quarter_1_absent": 2,
                              "attendance_quarter_2_absent": 3,
                              "attendance_quarter_3_absent": 4,
                              "attendance_quarter_4_absent": 1,
                              "attendance_quarter_1_tardy": 1,
                              "attendance_quarter_2_tardy": 2,
                              "attendance_quarter_3_tardy": 3,
                              "attendance_quarter_4_tardy": 2,
                              "attendance_quarter_1_present": 37,
                              "attendance_quarter_2_present": 35,
                              "attendance_quarter_3_present": 30,
                              "attendance_quarter_4_present": 35,
                              "final_grade": 90,
                              "year_final_grade": 87,
                              "quarter_average": 96.25,
                              "semestral_1_average": null,
                              "semestral_2_average": null,
                              "semestral_final": null,
                              "final_semestral_1_attendance": null,
                              "final_semestral_2_attendance": null,
                              "final_quarter_attendance": 155,
                              "mid_quarter_remarks": null,
                              "final_quarter_remarks": null,
                              "attendance": null
                          }
                      ]
                  }
              ],
              "standardized_test": [
                  {
                      "student_test_id": 9,
                      "child_id": "231d28bb-1f92-11eb-8212-dafd2d0ae3ff",
                      "test_name": "sat",
                      "attempt": 1,
                      "grade_taken": 0,
                      "month_taken": "",
                      "score": 23,
                      "score_percentage": 0,
                      "ach_level": 0,
                      "school_percentage": 0,
                      "nationality_percentage": 0,
                      "district_percentage": 0,
                      "state_percentage": 0,
                      "attachment": null
                  }
              ]
          },
          {
              "app_group_id": "97754eb9-fc18-11ea-8212-dafd2d0ae3ff",
              "app_group_name": "New group",
              "app_id": "31cf7ea6-1f93-11eb-8212-dafd2d0ae3ff",
              "child_id": "31ca6097-1f93-11eb-8212-dafd2d0ae3ff",
              "firstname": "jj",
              "lastname": "hjhhj",
              "form_contents": null,
              "cumulative_grades": [
                  {
                      "student_grade_cumulative_id": 4,
                      "app_id": null,
                      "app_group_id": "97754eb9-fc18-11ea-8212-dafd2d0ae3ff",
                      "app_group_name": null,
                      "application_type": "bcombs",
                      "child_id": "31ca6097-1f93-11eb-8212-dafd2d0ae3ff",
                      "form_contents": null,
                      "year_level": 5,
                      "designation": null,
                      "school_type": "Test",
                      "school_name": "Harvard",
                      "school_year_start": 2020,
                      "school_year_end": 2021,
                      "school_year_frame": "quarter",
                      "class_name": "Test",
                      "class_type": "Test",
                      "class_teacher": null,
                      "attachment": null,
                      "firstname": null,
                      "lastname": null,
                      "gpa_sem_1": 0,
                      "gpa_sem_2": 0,
                      "gpa_final": 0,
                      "scale": 0,
                      "grades": [
                          {
                              "student_grade_cumulative_id": 4,
                              "class": "Basic Programming",
                              "subject": "Basic Programming",
                              "teacher_name": "Test",
                              "designation": "Test",
                              "grade_quarter_1": 99,
                              "grade_quarter_2": 99,
                              "grade_quarter_3": 99,
                              "grade_quarter_4": 88,
                              "letter_grade_quarter_1": "A",
                              "letter_grade_quarter_2": "B",
                              "letter_grade_quarter_3": "C",
                              "letter_grade_quarter_4": "B",
                              "attendance_quarter_1_total": 40,
                              "attendance_quarter_2_total": 40,
                              "attendance_quarter_3_total": 37,
                              "attendance_quarter_4_total": 38,
                              "attendance_quarter_1_absent": 2,
                              "attendance_quarter_2_absent": 3,
                              "attendance_quarter_3_absent": 4,
                              "attendance_quarter_4_absent": 1,
                              "attendance_quarter_1_tardy": 1,
                              "attendance_quarter_2_tardy": 2,
                              "attendance_quarter_3_tardy": 3,
                              "attendance_quarter_4_tardy": 2,
                              "attendance_quarter_1_present": 37,
                              "attendance_quarter_2_present": 35,
                              "attendance_quarter_3_present": 30,
                              "attendance_quarter_4_present": 35,
                              "final_grade": 90,
                              "year_final_grade": 87,
                              "quarter_average": 96.25,
                              "semestral_1_average": null,
                              "semestral_2_average": null,
                              "semestral_final": null,
                              "final_semestral_1_attendance": null,
                              "final_semestral_2_attendance": null,
                              "final_quarter_attendance": 155,
                              "mid_quarter_remarks": null,
                              "final_quarter_remarks": null,
                              "attendance": null
                          }
                      ]
                  }
              ],
              "standardized_test": [
                  {
                      "student_test_id": 10,
                      "child_id": "31ca6097-1f93-11eb-8212-dafd2d0ae3ff",
                      "test_name": "eog",
                      "attempt": 1,
                      "grade_taken": 0,
                      "month_taken": "",
                      "score": 32,
                      "score_percentage": 0,
                      "ach_level": 0,
                      "school_percentage": 0,
                      "nationality_percentage": 0,
                      "district_percentage": 0,
                      "state_percentage": 0,
                      "attachment": null
                  },
                  {
                      "student_test_id": 26,
                      "child_id": "31ca6097-1f93-11eb-8212-dafd2d0ae3ff",
                      "test_name": "act",
                      "attempt": 1,
                      "grade_taken": 0,
                      "month_taken": "",
                      "score": 0,
                      "score_percentage": 0,
                      "ach_level": 0,
                      "school_percentage": 0,
                      "nationality_percentage": 0,
                      "district_percentage": 0,
                      "state_percentage": 0,
                      "attachment": null
                  }
              ]
          },
          {
              "app_group_id": "97754eb9-fc18-11ea-8212-dafd2d0ae3ff",
              "app_group_name": "New group",
              "app_id": "6783a6c6-2e61-11eb-8212-dafd2d0ae3ff",
              "child_id": "67800541-2e61-11eb-8212-dafd2d0ae3ff",
              "firstname": "jen",
              "lastname": "agang",
              "form_contents": null,
              "cumulative_grades": [
                  {
                      "student_grade_cumulative_id": 5,
                      "app_id": null,
                      "app_group_id": "97754eb9-fc18-11ea-8212-dafd2d0ae3ff",
                      "app_group_name": null,
                      "application_type": "bcombs",
                      "child_id": "67800541-2e61-11eb-8212-dafd2d0ae3ff",
                      "form_contents": null,
                      "year_level": 5,
                      "designation": null,
                      "school_type": "Test",
                      "school_name": "Harvard",
                      "school_year_start": 2020,
                      "school_year_end": 2021,
                      "school_year_frame": "quarter",
                      "class_name": "Test",
                      "class_type": "Test",
                      "class_teacher": null,
                      "attachment": null,
                      "firstname": null,
                      "lastname": null,
                      "gpa_sem_1": 0,
                      "gpa_sem_2": 0,
                      "gpa_final": 0,
                      "scale": 0,
                      "grades": [
                          {
                              "student_grade_cumulative_id": 5,
                              "class": "Basic Programming",
                              "subject": "Basic Programming",
                              "teacher_name": "Test",
                              "designation": "Test",
                              "grade_quarter_1": 99,
                              "grade_quarter_2": 99,
                              "grade_quarter_3": 99,
                              "grade_quarter_4": 88,
                              "letter_grade_quarter_1": "A",
                              "letter_grade_quarter_2": "B",
                              "letter_grade_quarter_3": "C",
                              "letter_grade_quarter_4": "B",
                              "attendance_quarter_1_total": 40,
                              "attendance_quarter_2_total": 40,
                              "attendance_quarter_3_total": 37,
                              "attendance_quarter_4_total": 38,
                              "attendance_quarter_1_absent": 2,
                              "attendance_quarter_2_absent": 3,
                              "attendance_quarter_3_absent": 4,
                              "attendance_quarter_4_absent": 1,
                              "attendance_quarter_1_tardy": 1,
                              "attendance_quarter_2_tardy": 2,
                              "attendance_quarter_3_tardy": 3,
                              "attendance_quarter_4_tardy": 2,
                              "attendance_quarter_1_present": 37,
                              "attendance_quarter_2_present": 35,
                              "attendance_quarter_3_present": 30,
                              "attendance_quarter_4_present": 35,
                              "final_grade": 90,
                              "year_final_grade": 87,
                              "quarter_average": 96.25,
                              "semestral_1_average": null,
                              "semestral_2_average": null,
                              "semestral_final": null,
                              "final_semestral_1_attendance": null,
                              "final_semestral_2_attendance": null,
                              "final_quarter_attendance": 155,
                              "mid_quarter_remarks": null,
                              "final_quarter_remarks": null,
                              "attendance": null
                          }
                      ]
                  }
              ],
              "standardized_test": [
                  {
                      "student_test_id": 27,
                      "child_id": "67800541-2e61-11eb-8212-dafd2d0ae3ff",
                      "test_name": "act",
                      "attempt": 1,
                      "grade_taken": 0,
                      "month_taken": "",
                      "score": 0,
                      "score_percentage": 0,
                      "ach_level": 0,
                      "school_percentage": 0,
                      "nationality_percentage": 0,
                      "district_percentage": 0,
                      "state_percentage": 0,
                      "attachment": null
                  }
              ]
          },
          {
              "app_group_id": "97754eb9-fc18-11ea-8212-dafd2d0ae3ff",
              "app_group_name": "New group",
              "app_id": "a9e218e2-316f-11eb-8212-dafd2d0ae3ff",
              "child_id": "a9df5977-316f-11eb-8212-dafd2d0ae3ff",
              "firstname": "kkkkkkjhhjhhj",
              "lastname": "hhjhjhh",
              "form_contents": null,
              "cumulative_grades": [
                  {
                      "student_grade_cumulative_id": 6,
                      "app_id": null,
                      "app_group_id": "97754eb9-fc18-11ea-8212-dafd2d0ae3ff",
                      "app_group_name": null,
                      "application_type": "bcombs",
                      "child_id": "a9df5977-316f-11eb-8212-dafd2d0ae3ff",
                      "form_contents": null,
                      "year_level": 5,
                      "designation": null,
                      "school_type": "Test",
                      "school_name": "Harvard",
                      "school_year_start": 2020,
                      "school_year_end": 2021,
                      "school_year_frame": "quarter",
                      "class_name": "Test",
                      "class_type": "Test",
                      "class_teacher": null,
                      "attachment": null,
                      "firstname": null,
                      "lastname": null,
                      "gpa_sem_1": 0,
                      "gpa_sem_2": 0,
                      "gpa_final": 0,
                      "scale": 0,
                      "grades": [
                          {
                              "student_grade_cumulative_id": 6,
                              "class": "Basic Programming",
                              "subject": "Basic Programming",
                              "teacher_name": "Test",
                              "designation": "Test",
                              "grade_quarter_1": 99,
                              "grade_quarter_2": 99,
                              "grade_quarter_3": 99,
                              "grade_quarter_4": 88,
                              "letter_grade_quarter_1": "A",
                              "letter_grade_quarter_2": "B",
                              "letter_grade_quarter_3": "C",
                              "letter_grade_quarter_4": "B",
                              "attendance_quarter_1_total": 40,
                              "attendance_quarter_2_total": 40,
                              "attendance_quarter_3_total": 37,
                              "attendance_quarter_4_total": 38,
                              "attendance_quarter_1_absent": 2,
                              "attendance_quarter_2_absent": 3,
                              "attendance_quarter_3_absent": 4,
                              "attendance_quarter_4_absent": 1,
                              "attendance_quarter_1_tardy": 1,
                              "attendance_quarter_2_tardy": 2,
                              "attendance_quarter_3_tardy": 3,
                              "attendance_quarter_4_tardy": 2,
                              "attendance_quarter_1_present": 37,
                              "attendance_quarter_2_present": 35,
                              "attendance_quarter_3_present": 30,
                              "attendance_quarter_4_present": 35,
                              "final_grade": 90,
                              "year_final_grade": 87,
                              "quarter_average": 96.25,
                              "semestral_1_average": null,
                              "semestral_2_average": null,
                              "semestral_final": null,
                              "final_semestral_1_attendance": null,
                              "final_semestral_2_attendance": null,
                              "final_quarter_attendance": 155,
                              "mid_quarter_remarks": null,
                              "final_quarter_remarks": null,
                              "attendance": null
                          }
                      ]
                  }
              ],
              "standardized_test": [
                  {
                      "student_test_id": 28,
                      "child_id": "a9df5977-316f-11eb-8212-dafd2d0ae3ff",
                      "test_name": "act",
                      "attempt": 1,
                      "grade_taken": 0,
                      "month_taken": "",
                      "score": 0,
                      "score_percentage": 0,
                      "ach_level": 0,
                      "school_percentage": 0,
                      "nationality_percentage": 0,
                      "district_percentage": 0,
                      "state_percentage": 0,
                      "attachment": null
                  }
              ]
          },
          {
              "app_group_id": "97754eb9-fc18-11ea-8212-dafd2d0ae3ff",
              "app_group_name": "New group",
              "app_id": "b6705ab8-3180-11eb-8212-dafd2d0ae3ff",
              "child_id": "b6682f4d-3180-11eb-8212-dafd2d0ae3ff",
              "firstname": "bbbh",
              "lastname": "hh",
              "form_contents": null,
              "cumulative_grades": [
                  {
                      "student_grade_cumulative_id": 7,
                      "app_id": null,
                      "app_group_id": "97754eb9-fc18-11ea-8212-dafd2d0ae3ff",
                      "app_group_name": null,
                      "application_type": "bcombs",
                      "child_id": "b6682f4d-3180-11eb-8212-dafd2d0ae3ff",
                      "form_contents": null,
                      "year_level": 5,
                      "designation": null,
                      "school_type": "Test",
                      "school_name": "Harvard",
                      "school_year_start": 2020,
                      "school_year_end": 2021,
                      "school_year_frame": "quarter",
                      "class_name": "Test",
                      "class_type": "Test",
                      "class_teacher": null,
                      "attachment": null,
                      "firstname": null,
                      "lastname": null,
                      "gpa_sem_1": 0,
                      "gpa_sem_2": 0,
                      "gpa_final": 0,
                      "scale": 0,
                      "grades": [
                          {
                              "student_grade_cumulative_id": 7,
                              "class": "Basic Programming",
                              "subject": "Basic Programming",
                              "teacher_name": "Test",
                              "designation": "Test",
                              "grade_quarter_1": 99,
                              "grade_quarter_2": 99,
                              "grade_quarter_3": 99,
                              "grade_quarter_4": 88,
                              "letter_grade_quarter_1": "A",
                              "letter_grade_quarter_2": "B",
                              "letter_grade_quarter_3": "C",
                              "letter_grade_quarter_4": "B",
                              "attendance_quarter_1_total": 40,
                              "attendance_quarter_2_total": 40,
                              "attendance_quarter_3_total": 37,
                              "attendance_quarter_4_total": 38,
                              "attendance_quarter_1_absent": 2,
                              "attendance_quarter_2_absent": 3,
                              "attendance_quarter_3_absent": 4,
                              "attendance_quarter_4_absent": 1,
                              "attendance_quarter_1_tardy": 1,
                              "attendance_quarter_2_tardy": 2,
                              "attendance_quarter_3_tardy": 3,
                              "attendance_quarter_4_tardy": 2,
                              "attendance_quarter_1_present": 37,
                              "attendance_quarter_2_present": 35,
                              "attendance_quarter_3_present": 30,
                              "attendance_quarter_4_present": 35,
                              "final_grade": 90,
                              "year_final_grade": 87,
                              "quarter_average": 96.25,
                              "semestral_1_average": null,
                              "semestral_2_average": null,
                              "semestral_final": null,
                              "final_semestral_1_attendance": null,
                              "final_semestral_2_attendance": null,
                              "final_quarter_attendance": 155,
                              "mid_quarter_remarks": null,
                              "final_quarter_remarks": null,
                              "attendance": null
                          }
                      ]
                  }
              ],
              "standardized_test": []
          },
          {
              "app_group_id": "97754eb9-fc18-11ea-8212-dafd2d0ae3ff",
              "app_group_name": "New group",
              "app_id": "795f06b5-3188-11eb-8212-dafd2d0ae3ff",
              "child_id": "795c3a0b-3188-11eb-8212-dafd2d0ae3ff",
              "firstname": "jenny1",
              "lastname": "1",
              "form_contents": null,
              "cumulative_grades": [
                  {
                      "student_grade_cumulative_id": 8,
                      "app_id": null,
                      "app_group_id": "97754eb9-fc18-11ea-8212-dafd2d0ae3ff",
                      "app_group_name": null,
                      "application_type": "bcombs",
                      "child_id": "795c3a0b-3188-11eb-8212-dafd2d0ae3ff",
                      "form_contents": null,
                      "year_level": 5,
                      "designation": null,
                      "school_type": "Test",
                      "school_name": "Harvard",
                      "school_year_start": 2020,
                      "school_year_end": 2021,
                      "school_year_frame": "quarter",
                      "class_name": "Test",
                      "class_type": "Test",
                      "class_teacher": null,
                      "attachment": null,
                      "firstname": null,
                      "lastname": null,
                      "gpa_sem_1": 0,
                      "gpa_sem_2": 0,
                      "gpa_final": 0,
                      "scale": 0,
                      "grades": [
                          {
                              "student_grade_cumulative_id": 8,
                              "class": "Basic Programming",
                              "subject": "Basic Programming",
                              "teacher_name": "Test",
                              "designation": "Test",
                              "grade_quarter_1": 99,
                              "grade_quarter_2": 99,
                              "grade_quarter_3": 99,
                              "grade_quarter_4": 88,
                              "letter_grade_quarter_1": "A",
                              "letter_grade_quarter_2": "B",
                              "letter_grade_quarter_3": "C",
                              "letter_grade_quarter_4": "B",
                              "attendance_quarter_1_total": 40,
                              "attendance_quarter_2_total": 40,
                              "attendance_quarter_3_total": 37,
                              "attendance_quarter_4_total": 38,
                              "attendance_quarter_1_absent": 2,
                              "attendance_quarter_2_absent": 3,
                              "attendance_quarter_3_absent": 4,
                              "attendance_quarter_4_absent": 1,
                              "attendance_quarter_1_tardy": 1,
                              "attendance_quarter_2_tardy": 2,
                              "attendance_quarter_3_tardy": 3,
                              "attendance_quarter_4_tardy": 2,
                              "attendance_quarter_1_present": 37,
                              "attendance_quarter_2_present": 35,
                              "attendance_quarter_3_present": 30,
                              "attendance_quarter_4_present": 35,
                              "final_grade": 90,
                              "year_final_grade": 87,
                              "quarter_average": 96.25,
                              "semestral_1_average": null,
                              "semestral_2_average": null,
                              "semestral_final": null,
                              "final_semestral_1_attendance": null,
                              "final_semestral_2_attendance": null,
                              "final_quarter_attendance": 155,
                              "mid_quarter_remarks": null,
                              "final_quarter_remarks": null,
                              "attendance": null
                          }
                      ]
                  }
              ],
              "standardized_test": [
                  {
                      "student_test_id": 20,
                      "child_id": "795c3a0b-3188-11eb-8212-dafd2d0ae3ff",
                      "test_name": "sat",
                      "attempt": 1,
                      "grade_taken": 0,
                      "month_taken": "09/01/2020",
                      "score": 300,
                      "score_percentage": 0,
                      "ach_level": 0,
                      "school_percentage": 0,
                      "nationality_percentage": 0,
                      "district_percentage": 0,
                      "state_percentage": 0,
                      "attachment": null
                  }
              ]
          },
          {
              "app_group_id": "97754eb9-fc18-11ea-8212-dafd2d0ae3ff",
              "app_group_name": "New group",
              "app_id": "f93ac110-318c-11eb-8212-dafd2d0ae3ff",
              "child_id": "f937e032-318c-11eb-8212-dafd2d0ae3ff",
              "firstname": "jkkjj",
              "lastname": "jhjhj",
              "form_contents": null,
              "cumulative_grades": [],
              "standardized_test": [
                  {
                      "student_test_id": 19,
                      "child_id": "f937e032-318c-11eb-8212-dafd2d0ae3ff",
                      "test_name": "eog",
                      "attempt": 1,
                      "grade_taken": 0,
                      "month_taken": "09/01/2020",
                      "score": 100,
                      "score_percentage": 0,
                      "ach_level": 0,
                      "school_percentage": 0,
                      "nationality_percentage": 0,
                      "district_percentage": 0,
                      "state_percentage": 0,
                      "attachment": null
                  }
              ]
          },
          {
              "app_group_id": "97754eb9-fc18-11ea-8212-dafd2d0ae3ff",
              "app_group_name": "New group",
              "app_id": "6cc65aaf-3645-11eb-8212-dafd2d0ae3ff",
              "child_id": "6cc2c171-3645-11eb-8212-dafd2d0ae3ff",
              "firstname": "november",
              "lastname": "hdhsghshdgh",
              "form_contents": null,
              "cumulative_grades": [
                  {
                      "student_grade_cumulative_id": 9,
                      "app_id": null,
                      "app_group_id": "97754eb9-fc18-11ea-8212-dafd2d0ae3ff",
                      "app_group_name": null,
                      "application_type": "bcombs",
                      "child_id": "6cc2c171-3645-11eb-8212-dafd2d0ae3ff",
                      "form_contents": null,
                      "year_level": 5,
                      "designation": null,
                      "school_type": "Test",
                      "school_name": "Harvard",
                      "school_year_start": 2020,
                      "school_year_end": 2021,
                      "school_year_frame": "quarter",
                      "class_name": "Test",
                      "class_type": "Test",
                      "class_teacher": null,
                      "attachment": null,
                      "firstname": null,
                      "lastname": null,
                      "gpa_sem_1": 0,
                      "gpa_sem_2": 0,
                      "gpa_final": 0,
                      "scale": 0,
                      "grades": [
                          {
                              "student_grade_cumulative_id": 9,
                              "class": "Basic Programming",
                              "subject": "Basic Programming",
                              "teacher_name": "Test",
                              "designation": "Test",
                              "grade_quarter_1": 99,
                              "grade_quarter_2": 99,
                              "grade_quarter_3": 99,
                              "grade_quarter_4": 88,
                              "letter_grade_quarter_1": "A",
                              "letter_grade_quarter_2": "B",
                              "letter_grade_quarter_3": "C",
                              "letter_grade_quarter_4": "B",
                              "attendance_quarter_1_total": 40,
                              "attendance_quarter_2_total": 40,
                              "attendance_quarter_3_total": 37,
                              "attendance_quarter_4_total": 38,
                              "attendance_quarter_1_absent": 2,
                              "attendance_quarter_2_absent": 3,
                              "attendance_quarter_3_absent": 4,
                              "attendance_quarter_4_absent": 1,
                              "attendance_quarter_1_tardy": 1,
                              "attendance_quarter_2_tardy": 2,
                              "attendance_quarter_3_tardy": 3,
                              "attendance_quarter_4_tardy": 2,
                              "attendance_quarter_1_present": 37,
                              "attendance_quarter_2_present": 35,
                              "attendance_quarter_3_present": 30,
                              "attendance_quarter_4_present": 35,
                              "final_grade": 90,
                              "year_final_grade": 87,
                              "quarter_average": 96.25,
                              "semestral_1_average": null,
                              "semestral_2_average": null,
                              "semestral_final": null,
                              "final_semestral_1_attendance": null,
                              "final_semestral_2_attendance": null,
                              "final_quarter_attendance": 155,
                              "mid_quarter_remarks": null,
                              "final_quarter_remarks": null,
                              "attendance": null
                          }
                      ]
                  }
              ],
              "standardized_test": []
          },
          {
              "app_group_id": "97754eb9-fc18-11ea-8212-dafd2d0ae3ff",
              "app_group_name": "New group",
              "app_id": "b6b030ed-4467-11eb-8212-dafd2d0ae3ff",
              "child_id": "b6a31d6e-4467-11eb-8212-dafd2d0ae3ff",
              "firstname": "ggffgf",
              "lastname": "fffff",
              "form_contents": null,
              "cumulative_grades": [
                  {
                      "student_grade_cumulative_id": 10,
                      "app_id": null,
                      "app_group_id": "97754eb9-fc18-11ea-8212-dafd2d0ae3ff",
                      "app_group_name": null,
                      "application_type": "bcombs",
                      "child_id": "b6a31d6e-4467-11eb-8212-dafd2d0ae3ff",
                      "form_contents": null,
                      "year_level": 5,
                      "designation": null,
                      "school_type": "Test",
                      "school_name": "Harvard",
                      "school_year_start": 2020,
                      "school_year_end": 2021,
                      "school_year_frame": "quarter",
                      "class_name": "Test",
                      "class_type": "Test",
                      "class_teacher": null,
                      "attachment": null,
                      "firstname": null,
                      "lastname": null,
                      "gpa_sem_1": 0,
                      "gpa_sem_2": 0,
                      "gpa_final": 0,
                      "scale": 0,
                      "grades": [
                          {
                              "student_grade_cumulative_id": 10,
                              "class": "Basic Programming",
                              "subject": "Basic Programming",
                              "teacher_name": "Test",
                              "designation": "Test",
                              "grade_quarter_1": 99,
                              "grade_quarter_2": 99,
                              "grade_quarter_3": 99,
                              "grade_quarter_4": 88,
                              "letter_grade_quarter_1": "A",
                              "letter_grade_quarter_2": "B",
                              "letter_grade_quarter_3": "C",
                              "letter_grade_quarter_4": "B",
                              "attendance_quarter_1_total": 40,
                              "attendance_quarter_2_total": 40,
                              "attendance_quarter_3_total": 37,
                              "attendance_quarter_4_total": 38,
                              "attendance_quarter_1_absent": 2,
                              "attendance_quarter_2_absent": 3,
                              "attendance_quarter_3_absent": 4,
                              "attendance_quarter_4_absent": 1,
                              "attendance_quarter_1_tardy": 1,
                              "attendance_quarter_2_tardy": 2,
                              "attendance_quarter_3_tardy": 3,
                              "attendance_quarter_4_tardy": 2,
                              "attendance_quarter_1_present": 37,
                              "attendance_quarter_2_present": 35,
                              "attendance_quarter_3_present": 30,
                              "attendance_quarter_4_present": 35,
                              "final_grade": 90,
                              "year_final_grade": 87,
                              "quarter_average": 96.25,
                              "semestral_1_average": null,
                              "semestral_2_average": null,
                              "semestral_final": null,
                              "final_semestral_1_attendance": null,
                              "final_semestral_2_attendance": null,
                              "final_quarter_attendance": 155,
                              "mid_quarter_remarks": null,
                              "final_quarter_remarks": null,
                              "attendance": null
                          }
                      ]
                  }
              ],
              "standardized_test": []
          }
      ]//action.payload
      }
    case actionType.CUMULATIVE_GRADE_BY_USER_COMPLETED: 
      return {
        ...state,
        individualList: action.payload
      }
    case actionType.ADD_UPDATE_STUDENT_STANDARD_TEST_COMPLETED:
      return {
        ...state,
        addUpdate: action.payload,
        stUpdated: true
      }
    case actionType.DELETE_STUDENT_STANDARDIZED_TEST_COMPLETED:
      return {
        ...state,
        stUpdated: true
      }
    case actionType.CLEAR_GRADES:
      return {
        ...state,
        stUpdated: false
      }
    default:
      return state;
  }
}
